### ISSUE TITLE
Package CJK Error: Invalid character code

### ISSUE THREAD

**Issue by Qinghev** [leaf-hsiao/HNUThesisTemplate#1]
I can't type any Chinese character in reference.
If I did, then the error showed up.

Help, please.

---------here is the error ------------
! Package CJK Error: Invalid character code.

See the CJK package documentation for explanation.
Type H<return> for immediate help.
...

1.5 \newblock 电法勘探正演

？

**Comment by leaf-hsiao** [comment]
Did you save your `reference.bib` with UTF-8 encoding?

**Comment by Qinghev** [comment]
how to save reference.bib with UTF-8 encoding?

I opened it through notepad, then added some contents and saved them.
I ran latex-->bibtex-->latex. While the contents were English, it worked well.
The error showed up after I inserted Chinese items.

I opened reference.bbl through notepad, the content was right. 
If I ignore the problem, then all the Chinese items are unintelligible text.

**Comment by leaf-hsiao** [comment]
Notepad add a BOM in your file. Use Notepad++, VSCode or other editors instead.

**Comment by Qinghev** [comment]
How to add a BOM?
I use Ctex to create a new bib document, still not working.

**Comment by Qinghev** [comment]
Problem sovled. 
reference.bib was saved with ANSI encoding, I save the document as ... , then I could change the encoding method to UTF-8.
Thank you.
